server:
  foo: bar
  environments:
    - name: dev
      services: bookstore
    - name: batch
      services: warehouse

application:
  log-level: DEBUG
  eoc-mode: false
  processing:
    always-success: true
    keep-token: true
  prolong:
    protocol: http
    jitter: 0.2
  auth:
    - location: foo/api/front/auth/pub-keys
      prolong-url: foo/api/front/auth/prolong
      refresh: 5
      hostnames:
        - localhost
        - "localhost:8080"
