server:
  foo: bar
  environments:
    - name: dev
      services: bookstore
    - name: batch
      services: warehouse

application:
  log-level: DEBUG
  eoc-mode: false
  processing:
    always-success: false
    keep-token: true
  # prolong:
  #   protocol: http
  # auth:
  #   - location: ${quarkus.mockserver.endpoint}/api/front/auth/pub-keys
  #     prolong-url: ${quarkus.mockserver.endpoint}/api/front/auth/prolong
  #     refresh: 5
  #     hostnames:
  #       - localhost
  #       - "localhost:8080"
